language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
        - HTML_CSS_JS-Reference/example-react-app
before_script: cd HTML_CSS_JS-Reference/example-react-app/node_modules
script:
    - npm test
    - npm run build
deploy:
    provider: surge
    skip_cleanup: true
    domain: example-react-app.surge.sh
    project: ./build/
on:
    branch: master
